layout_spectrum: 0.04859041911549866
typography_spectrum: 0.13440496916882694
color:
  brandStrength: 0.234804559731856
  lightness: 0.5214796243235469
  saturation: 0.15275794663466513
  rhythmicContrast: 0.32940908800810575
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
author:
  name: Leandro Lagera
  email: llagera@foodnomad.net
  url: www.foodnomad.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ab7c1be-4e91-4e69-bf27-f04db6572b48.jpg
name: Food Nomad
navigation:
  - name: Old Site
    url: 'http://www.foodnomad.net'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06fc001e-e5cd-4974-95cd-90fa42053827.jpg
